# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft / Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

# Mod
mod_id=sofmenu
mod_name=SOF Menu
mod_license=MIT
mod_version=1.20.1
mod_group_id=com.canoestudios
mod_authors=CanoeStudio
mod_description=Custom main menu, loading screens, window title and more for the SOF modpack.

# Mappings
mapping_channel=official
mapping_version=1.20.1
